language: cpp
dist: focal

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-11 g++-11

install:
  - make get-deps

script:
  - export CC=gcc-11
  - export CXX=g++-11
  - make
  - make test
